In [1]:
import numpy as np
import pandas as pd
import shapefile as shp
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
sns.set(style="whitegrid", palette="pastel", color_codes=True)
sns.mpl.rc("figure", figsize=(10,6))

In [3]:
shp_path = "./us_data/tl_2017_us_state.shp"
sf = shp.Reader(shp_path)

In [4]:
print(len(sf.shapes()))

56

In [5]:
def read_shapefile(sf):
    fields = [x[0] for x in sf.fields][1:]
    records = sf.records()
    shps = [s.points for s in sf.shapes()]
    
    df = pd.DataFrame(columns=fields, data=records)
    df = df.assign(coords=shps)
    
    return df

In [6]:
df = read_shapefile(sf)
print(df.shape)

(56, 15)

In [7]:
df

,REGION,DIVISION,STATEFP,STATENS,GEOID,STUSPS,NAME,LSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,coords
0,3,5,54,01779805,54,WV,West Virginia,00,G4000,A,62265662566,489840834,+38.6472854,-080.6183274,"[(-81.747254, 39.095379), (-81.746354, 39.0965..."
1,3,5,12,00294478,12,FL,Florida,00,G4000,A,138911437206,31398800291,+28.4574302,-082.4091478,"[(-82.987477, 24.625379), (-82.987477, 24.6254..."
2,2,3,17,01779784,17,IL,Illinois,00,G4000,A,143784114293,6211277447,+40.1028754,-089.1526108,"[(-91.185295, 40.637803), (-91.1751, 40.643027..."
3,2,4,27,00662849,27,MN,Minnesota,00,G4000,A,206229176104,18944967530,+46.3158148,-094.1996628,"[(-96.784381, 46.630503999999995), (-96.784337..."
4,3,5,24,01714934,24,MD,Maryland,00,G4000,A,25150696145,6980371026,+38.9466584,-076.6744939,"[(-77.45880799999999, 39.22027), (-77.45866099..."
5,1,1,44,01219835,44,RI,Rhode Island,00,G4000,A,2677997539,1323452846,+41.5974187,-071.5272723,"[(-71.67880699999999, 41.158912), (-71.676264,..."
6,4,8,16,01779783,16,ID,Idaho,00,G4000,A,214048160737,2393355752,+44.3484222,-114.5588538,"[(-116.899711, 44.840609), (-116.89967, 44.840..."
7,1,1,33,01779794,33,NH,New Hampshire,00,G4000,A,23187445452,1028643155,+43.6726907,-071.5843145,"[(-72.329899, 43.600214), (-72.329838, 43.6002..."
8,3,5,37,01027616,37,NC,North Carolina,00,G4000,A,125919712692,13470113896,+35.5397100,-079.1308636,"[(-82.416738, 36.072827), (-82.416601, 36.0730..."
9,1,1,50,01779802,50,VT,Vermont,00,G4000,A,23873457570,1031134839,+44.0604795,-072.6733274,"[(-73.313283, 44.26413), (-73.312741, 44.26541..."
10,1,1,09,01779780,09,CT,Connecticut,00,G4000,A,12542619303,1815495323,+41.5798637,-072.7466572,"[(-73.51808, 41.666723), (-73.51807099999999, ..."
11,3,5,10,01779781,10,DE,Delaware,00,G4000,A,5047241079,1398670234,+38.9986239,-075.4416920,"[(-75.760074, 39.296819), (-75.76010099999999,..."
12,4,8,35,00897535,35,NM,New Mexico,00,G4000,A,314191415563,733669653,+34.4346843,-106.1316181,"[(-106.006316, 36.995267), (-106.005314, 36.99..."
13,4,9,06,01779778,06,CA,California,00,G4000,A,403483182192,20484637928,+37.1551773,-119.5434183,"[(-119.636068, 33.280713), (-119.634795, 33.28..."
14,1,2,34,01779795,34,NJ,New Jersey,00,G4000,A,19049723313,3542963551,+40.1072744,-074.6652012,"[(-75.1896, 40.591775999999996), (-75.18976599..."
15,2,3,55,01779806,55,WI,Wisconsin,00,G4000,A,140275464079,29359527964,+44.6309071,-089.7093916,"[(-92.887067, 45.644148), (-92.886712, 45.6445..."
16,4,9,41,01155107,41,OR,Oregon,00,G4000,A,248604328809,6195045325,+43.9717125,-120.6229578,"[(-124.065448, 45.783054), (-124.062056, 45.78..."
17,2,4,31,01779792,31,NE,Nebraska,00,G4000,A,198957965731,1370523694,+41.5433014,-099.8118616,"[(-104.052645, 42.001718), (-104.052634, 42.00..."
18,1,2,42,01779798,42,PA,Pennsylvania,00,G4000,A,115881477379,3397554419,+40.9024957,-077.8334514,"[(-80.51935399999999, 41.849562999999996), (-8..."
19,4,9,53,01779804,53,WA,Washington,00,G4000,A,172111800165,12560067439,+47.4073238,-120.5757999,"[(-123.247919, 48.284558), (-123.247794, 48.28..."
20,3,7,22,01629543,22,LA,Louisiana,00,G4000,A,111904803121,23746413153,+30.8634368,-091.7987173,"[(-92.069105, 33.008162999999996), (-92.069043..."
21,3,5,13,01705317,13,GA,Georgia,00,G4000,A,149177524294,4733385577,+32.6295789,-083.4235109,"[(-85.38658099999999, 33.901719), (-85.386595,..."
22,3,6,01,01779775,01,AL,Alabama,00,G4000,A,131174431216,4592944701,+32.7396323,-086.8434593,"[(-88.139988, 34.581703), (-88.139969, 34.5818..."
23,4,8,49,01455989,49,UT,Utah,00,G4000,A,212884846341,7000199770,+39.3349925,-111.6563326,"[(-114.047026, 39.906096999999995), (-114.0470..."
24,2,3,39,01085497,39,OH,Ohio,00,G4000,A,105833282399,10264451012,+40.4149297,-082.7119975,"[(-84.803251, 40.989394), (-84.803242, 40.9910..."
25,3,7,48,01779801,48,TX,Texas,00,G4000,A,676641930188,19017521093,+31.4347032,-099.2818238,"[(-103.98017899999999, 32.000125), (-103.97993..."
26,4,8,08,01779779,08,CO,Colorado,00,G4000,A,268425964573,1178495763,+38.9938482,-105.5083165,"[(-109.050949, 40.222646999999995), (-109.0509..."
27,3,5,45,01779799,45,SC,South Carolina,00,G4000,A,77862731483,5071381300,+33.8741776,-080.8542639,"[(-82.741007, 34.208861999999996), (-82.741172..."
28,3,7,40,01102857,40,OK,Oklahoma,00,G4000,A,177664450004,3373087228,+35.5900512,-097.4868149,"[(-100.003762, 36.499849), (-100.00397, 36.499..."
29,3,6,47,01325873,47,TN,Tennessee,00,G4000,A,106798015774,2354836197,+35.8585557,-086.3493580,"[(-82.222064, 36.15696), (-82.222145, 36.15692..."
30,4,8,56,01779807,56,WY,Wyoming,00,G4000,A,251465641446,1860628076,+42.9918024,-107.5419255,"[(-111.044893, 43.315719), (-111.044941, 43.31..."
31,4,9,15,01779782,15,HI,Hawaii,00,G4000,A,16634117742,11777681513,+22.0120383,-159.7059653,"[(-166.386532, 23.846363), (-166.3842839999999..."
32,2,4,38,01779797,38,ND,North Dakota,00,G4000,A,178710423375,4400396641,+47.4421740,-100.4608258,"[(-104.045371, 47.330127999999995), (-104.0453..."
33,3,6,21,01779786,21,KY,Kentucky,00,G4000,A,102266092821,2388731561,+37.5336844,-085.2929801,"[(-89.571203, 36.552141999999996), (-89.571137..."
34,9,0,78,01802710,78,VI,United States Virgin Islands,00,G4000,A,348013711,1550244357,+18.3267484,-064.9712505,"[(-64.95671399999999, 17.678977), (-64.956384,..."
35,9,0,69,01779809,69,MP,Commonwealth of the Northern Mariana Islands,00,G4000,A,472284356,4644260632,+14.9367835,+145.6010210,"[(145.55883599999999, 16.374152), (145.571326,..."
36,9,0,66,01802705,66,GU,Guam,00,G4000,A,543558310,934334983,+13.4382886,+144.7729493,"[(144.563426, 13.448065), (144.563574, 13.4509..."
37,1,1,23,01779787,23,ME,Maine,00,G4000,A,79885808421,11748168571,+45.4092789,-068.6665979,"[(-70.989122, 43.792113), (-70.989132, 43.7925..."
38,1,2,36,01779796,36,NY,New York,00,G4000,A,122048992746,19247151848,+42.9133974,-075.5962723,"[(-74.047133, 40.690542), (-74.04710399999999,..."
39,4,8,32,01779793,32,NV,Nevada,00,G4000,A,284329327067,2047350803,+39.3310928,-116.6151469,"[(-119.324184, 41.993922999999995), (-119.3236..."
40,4,9,02,01785533,02,AK,Alaska,00,G4000,A,1478588231566,277723861311,+63.2813242,-152.5730397,"[(172.34933999999998, 52.922194), (172.353886,..."
41,9,0,60,01802701,60,AS,American Samoa,00,G4000,A,197759070,1307243753,-14.2668475,-170.6671854,"[(-171.14118100000002, -11.046607999999999), (..."
42,2,3,26,01779789,26,MI,Michigan,00,G4000,A,146488062160,103998746281,+44.8441757,-085.6604930,"[(-86.46412, 45.32481), (-86.464518, 45.324974..."
43,3,7,05,00068085,05,AR,Arkansas,00,G4000,A,134768100673,2963631791,+34.8955256,-092.4446262,"[(-94.55217999999999, 36.102236), (-94.55224, ..."
44,3,6,28,01779790,28,MS,Mississippi,00,G4000,A,121530256608,3930182746,+32.6864714,-089.6561377,"[(-90.955974, 34.120125), (-90.95723199999999,..."
45,2,4,29,01779791,29,MO,Missouri,00,G4000,A,178052037005,2488190402,+38.3507500,-092.4567826,"[(-94.60803299999999, 38.847207), (-94.6080269..."
46,4,8,30,00767982,30,MT,Montana,00,G4000,A,376960880222,3871059371,+47.0511771,-109.6348174,"[(-115.629488, 47.47961), (-115.629825, 47.479..."
47,2,4,20,00481813,20,KS,Kansas,00,G4000,A,211753159949,1346325556,+38.4985464,-098.3834298,"[(-102.045212, 38.697567), (-102.04521, 38.704..."
48,2,3,18,00448508,18,IN,Indiana,00,G4000,A,92787765193,1539541677,+39.9030256,-086.2839503,"[(-87.526589, 40.476876), (-87.52658199999999,..."
49,9,0,72,01779808,72,PR,Puerto Rico,00,G4000,A,8868734851,4922543816,+18.2176480,-066.4107992,"[(-67.998691, 18.170759999999998), (-67.998691..."
50,2,4,46,01785534,46,SD,South Dakota,00,G4000,A,196345228871,3384471850,+44.4467957,-100.2381762,"[(-100.499371, 45.943653), (-100.481922, 45.94..."
51,1,1,25,00606926,25,MA,Massachusetts,00,G4000,A,20204287539,7130763257,+42.1565196,-071.4895915,"[(-71.49825899999999, 42.017272), (-71.499065,..."
52,3,5,51,01779803,51,VA,Virginia,00,G4000,A,102254240128,8532012665,+37.5222512,-078.6681938,"[(-77.328318, 39.057677999999996), (-77.328302..."
53,3,5,11,01702382,11,DC,District of Columbia,00,G4000,A,158351639,18675956,+38.9041031,-077.0172290,"[(-77.119751, 38.934349999999995), (-77.118861..."
54,2,4,19,01779785,19,IA,Iowa,00,G4000,A,144664158135,1081293682,+42.0700243,-093.4933473,"[(-96.49877599999999, 42.561043), (-96.4870749..."
55,4,8,04,01779777,04,AZ,Arizona,00,G4000,A,294198661567,1027245114,+34.2039355,-111.6063565,"[(-114.516454, 33.027617), (-114.516639, 33.02..."

In [8]:
def fip_to_state(fip):
    fip = str(fip)
    if len(fip) < 2:
        fip = '0' + fip
     
    print(fip, df[df.GEOID == fip].index)
    return df[df.GEOID == fip].index.values[0]

In [9]:
def state_to_id(state):
    return df[df.NAME == state].index.values[0]

In [10]:
def plot_shape(id, s=None):
    plt.figure()
    ax = plt.axes()
    ax.set_aspect('equal')
    shape_ex = sf.shape(id)
    x_lon = np.zeros((len(shape_ex.points), 1))
    y_lat = np.zeros((len(shape_ex.points), 1))
    
    for ip in range(len(shape_ex.points)):
        x_lon[ip] = shape_ex.points[ip][0]
        y_lat[ip] = shape_ex.points[ip][1]
        
    plt.plot(x_lon, y_lat)
    plt.xlim(shape_ex.bbox[0], shape_ex.bbox[2])
    return x0, y0

In [11]:
def plot(title, ids, sf, x_lim=None, y_lim=None, figsize=(11,9), color='r'):
       
    plt.figure(figsize = figsize)
    fig, ax = plt.subplots(figsize=figsize)
    fig.suptitle(title, fontsize=16)
    

    s_id = 0
    for shape in sf.shapeRecords():
        if(s_id not in no_print):
            x = [i[0] for i in shape.shape.points[:]]
            y = [i[1] for i in shape.shape.points[:]]
            plt.plot(x, y, 'k')
        s_id = s_id + 1

    for id in ids:
        shape_ex = sf.shape(id)
        x_lon = np.zeros((len(shape_ex.points),1))
        y_lat = np.zeros((len(shape_ex.points),1))
        for ip in range(len(shape_ex.points)):
            x_lon[ip] = shape_ex.points[ip][0]
            y_lat[ip] = shape_ex.points[ip][1]
        ax.fill(x_lon, y_lat, color)
        
        x0 = np.mean(x_lon)
        y0 = np.mean(y_lat)
        plt.text(x0, y0, id, fontsize=10)
    
    if (x_lim != None) & (y_lim != None):     
        plt.xlim(x_lim)
        plt.ylim(y_lim)

In [12]:
def remove_dups(data):
    da = []
    for d in data:
        if(d in da):
            pass
        else:
            da.append(d)
    return da

In [13]:
def lists_to_listi(ls):
    li = []
    for e in ls:
        li.append(int(e))
    return li

In [14]:
from colour import Color
def colors_calc(data, c1, c2):
    vals = lists_to_listi(data.values())
    rd = remove_dups(sorted(vals))
    da = sorted(vals)
    cs = {}
    c = Color(c2)
    colors = list(c.range_to(Color(c1), len(rd)))

    prev = 0
    dups = 0
    for i in range(len(da)):
        if i == 0:
            cs[da[i]] = colors[i].hex
        else:
            if da[prev] != da[i]:
                cs[da[i]] = colors[(i - dups)].hex
            else:
                dups += 1
        prev = i

    cs[0] = "#ffffff"
#     Un-comment below to see a graphical representation of the gradient colors used.
#     sns.palplot(list(cs.values()), 0.1 * len(rd))
    return cs

In [15]:
def sid_to_s(sid):
    n = df['NAME']
    return n[sid]

In [16]:
def plot_states_data(sf, title, states, data, print_id=False, save_fig=True):
    colors = colors_calc(data, "green", "red")
    df = read_shapefile(sf)
    state_id = []
    
    no_print = ["Hawaii", "Guam", "Puerto Rico", "Alaska", "Northern Mariana Islands", "Virgin Islands", "American Samoa"]
    for i in range(len(states)):
        if(not (df[df.NAME == states[i]].empty) and states[i] not in no_print):
            state_id.append(df[df.NAME == states[i]].index.values[0])
    plot_map_fill_multiple_ids_tone(sf, title, state_id, data, print_id, colors, x_lim = None, y_lim = None, savefigb=save_fig)

In [17]:
def plot_map_fill_multiple_ids_tone(sf, title, state, data, print_id, colors, x_lim =None, y_lim =None, figsize = (11,9), savefigb=True):
    plt.figure(figsize=figsize)
    fig, ax = plt.subplots(figsize = figsize, dpi=75)
    fig.suptitle(str(title)[:10] + ' GDP per Case', fontsize=16)
    ax.set_aspect('equal')
    
    sip = []
    
    for i in range(len(state)):
        id = state[i]
        state_name = sid_to_s(id)
        cases = int(data[state_name])
        
#         print(state_name, id)
        
        shape_ex = sf.shape(id)
        x_lon = np.zeros((len(shape_ex.points),1))
        y_lat = np.zeros((len(shape_ex.points),1))
        
        for ip in range(len(shape_ex.points)):
            x_lon[ip] = shape_ex.points[ip][0]
            y_lat[ip] = shape_ex.points[ip][1]
        
        
        ax.fill(x_lon,y_lat, colors[cases])
        
        if print_id != False:
            x0 = np.mean(x_lon)
            y0 = np.mean(y_lat)
            ''' str(cases)'''
            plt.text(x0, y0,  str(cases), fontsize='smaller', va='center', ha='center')
    
    no_print = [40, 31, 41, 35, 36, 49, 34]
    s_id = 0
    for shape in sf.shapeRecords():
        if(s_id not in no_print):
            
            sn = sid_to_s(s_id)
            ss = None
            
            x = [i[0] for i in shape.shape.points[:]]
            y = [i[1] for i in shape.shape.points[:]]
            if ss is not None:
                if ss == title or title > ss:
#                     print(sn, "SIP")
                    ax.plot(x, y, c='#0000ff', linewidth=2)
                else:
                    ax.plot(x, y, 'k')
            else:
                if title == get_date('2020-04-05'):
                    ax.plot(x, y, c='#ff0000')
                else:
                    ax.plot(x, y, c='k')
        
        s_id = s_id + 1
    

        if (x_lim != None) & (y_lim != None):     
            plt.xlim(x_lim)
            plt.ylim(y_lim)
        if savefigb:
            fig.savefig('./photos/' + str(title)[:10])
            plt.close(fig)

In [18]:
import csv
import datetime

In [19]:
def get_date(s):
    return datetime.datetime.strptime(s, '%Y-%m-%d')

In [20]:
def get_date_from_covid(ind, file='us-states-covid.csv'):
    i = 0
    pd = get_date('2019-12-30')
    with open(file) as cf:
        cr = csv.reader(cf, delimiter=',')
        for r in cr:
            if r[0] == 'date':
                pass
            else:
                date = get_date(r[0])

                #  Next Day
                if date > pd:
                    if i == ind:
                        return date
                    i += 1
                    pd = date

In [21]:
def parse_covid(file):
    dates = []
    with open(file) as cf:
        cols = []
        cr = csv.reader(cf, delimiter=',')
        
        lc = 0
        prev_date = get_date('2019-12-30')
        i = -1

        for r in cr:
            if lc == 0:
                cols = r
                print(f'{cols}')
                lc += 1
            else:
                date = get_date(r[0])
                # print(prev_date, date)
                
                #  Next Day
                if date > prev_date:
                    # print('New day')
                    i += 1
                    prev_date = date
                    dates.append([])
                    dates[i].append([r[1], r[3]])

                # Same day
                elif date == prev_date:
                    dates[i].append([r[1], r[3]])
                else:
                    print("ERROR")
                    exit(0)
                    
                lc += 1
        print(f'Processed {lc} lines')
        return dates

In [22]:
def parse_gdp(file):
    s_gdp = {}
    with open(file) as cf:
        cols = []
        cr = csv.reader(cf, delimiter=',')
        lc = 0
        for r in cr:
            if lc == 0:
                cols = r
                lc += 1
            else:
                s = r[0]
                gdp = r[1]
                s_gdp[s] = gdp
                lc += 1
    return s_gdp

In [23]:
def get_gdp(state):
    g = parse_gdp('gdp-q4-2019.csv')
    if(state in g.keys()):
        return g[state]
    else:
        return 1

In [24]:
cases = parse_covid('us-states-covid.csv')

['date', 'state', 'fips', 'cases', 'deaths']
Processed 2722 lines

In [25]:
def create_dict(cases):
    ca = {}
    for c in cases:
        state = c[0]
        cases = c[1]
        gdp = get_gdp(state)
        if(cases != "0"):
            diff = float(gdp)/float(cases)
        else:
            diff = 1
        ca[c[0]] = diff
    return ca

In [26]:
def parse_date_entry(ca):
    states = []
    cases = []
    
    for c in ca:
        states.append(c[0])
        cases.append(int(c[1]))
    return states, cases

In [27]:
def show_covid(i, _cases):
    states, _ = parse_date_entry(_cases[i])
    cases = create_dict(_cases[i])
    date = get_date_from_covid(i)
    print(cases)
    plot_states_data(sf, date, states, cases, True, save_fig=True)

In [28]:
import time
start_time = time.time()
show_covid(len(cases)-1, cases)
print("--- %s seconds ---" % (time.time() - start_time))

{'Alabama': 46.09176841276093, 'Alaska': 174.79310344827587, 'American Samoa': 1, 'Arizona': 73.56279620853081, 'Arkansas': 68.62252663622526, 'California': 94.0065855531274, 'Colorado': 39.220957846823666, 'Connecticut': 14.584153419126924, 'Delaware': 27.83606557377049, 'District of Columbia': 50.64263751281175, 'Florida': 41.086062846580404, 'Georgia': 33.8986827126362, 'Guam': 0.0012330456226880395, 'Hawaii': 170.47750865051904, 'Idaho': 50.22283272283272, 'Illinois': 28.847054716262537, 'Indiana': 32.66583946602773, 'Iowa': 62.10141732283464, 'Kansas': 86.51058591826687, 'Kentucky': 71.33245901639344, 'Louisiana': 10.889817722138401, 'Maine': 78.21828571428571, 'Maryland': 31.738672902660042, 'Massachusetts': 15.241227959538884, 'Michigan': 17.181914993579102, 'Minnesota': 156.23765182186236, 'Mississippi': 26.690824468085108, 'Missouri': 58.00172205958326, 'Montana': 122.28175519630484, 'Nebraska': 78.33616504854369, 'Nevada': 47.103394255874676, 'New Hampshire': 62.084312370421564, 'New Jersey': 7.346485597819967, 'New Mexico': 53.405885337392185, 'New York': 7.076241299491402, 'North Carolina': 88.17016558249557, 'North Dakota': 91.54704944178629, 'Northern Mariana Islands': 0.07142857142857142, 'Ohio': 54.70733028872204, 'Oklahoma': 77.38097014925373, 'Oregon': 130.58179959100204, 'Pennsylvania': 24.2494633142185, 'Puerto Rico': 0.0007987220447284345, 'Rhode Island': 12.660314341846759, 'South Carolina': 56.31178193286776, 'South Dakota': 32.0813056379822, 'Tennessee': 54.9880256593015, 'Texas': 95.68795210775754, 'Utah': 59.761282290694055, 'Vermont': 43.224264705882355, 'Virgin Islands': 0.018518518518518517, 'Virginia': 62.49677419354839, 'Washington': 50.07694200639816, 'West Virginia': 86.4614537444934, 'Wisconsin': 78.22227161591465, 'Wyoming': 125.53312302839117}
--- 24.302369832992554 seconds ---